export enum MysqlErrorCodes {
  ER_DUP_ENTRY = 'ER_DUP_ENTRY',
  ER_ROW_IS_REFERENCED = 'ER_ROW_IS_REFERENCED',
  ER_NO_REFERENCED_ROW = 'ER_NO_REFERENCED_ROW',
  ER_DATA_TOO_LONG = 'ER_DATA_TOO_LONG',
  ER_CHECK_CONSTRAINT_VIOLATED = 'ER_CHECK_CONSTRAINT_VIOLATED',
  ER_INVALID_DEFAULT = 'ER_INVALID_DEFAULT',
  ER_SYNTAX_ERROR = 'ER_SYNTAX_ERROR',
  ER_WRONG_VALUE_COUNT = 'ER_WRONG_VALUE_COUNT',
  ER_UNSUPPORTED_EXTENSION = 'ER_UNSUPPORTED_EXTENSION',
  ER_QUERY_INTERRUPTED = 'ER_QUERY_INTERRUPTED',
  ER_LOCK_WAIT_TIMEOUT = 'ER_LOCK_WAIT_TIMEOUT',
}
